### ISSUE TITLE
Set up gitlab pushes for chart deployment

### ISSUE THREAD

**Issue by aanthonyrizzo** [CentML/coreweave-app#3]
TODO: Fill out spec

**Comment by aanthonyrizzo** [comment]
@jfeldman325 when you can please fill out this ticket w/ the actionable items for the CentML team (if there are any)

**Comment by jfeldman325** [comment]
Hey there! Did a quick review and here's what I have:

1) [https://github.com/CentML/coreweave-app/blob/main/centml/values.yaml We will ](https://github.com/CentML/coreweave-app/blob/main/centml/templates/notebook-deployment.yaml) is invalid, please review our documentation for valid labels, I would suggest adding a key allowing users to specify their own affinity or need be the specific GPU type. An example would be
```
<---- values.yaml ----->
affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - "{{.Values.nodeSelector.region}}"
            - key:  gpu.nvidia.com/class
              operator: In
              values:
                - A40
 ```
 as your default affinity, then in your deployment you would simply put 
 ```
 affinity:
 {{ tpl (.Values.affinity | toYaml) $ | indent 2 }}
 ```
 the preffered scheduling terms are invalid as well https://github.com/CentML/coreweave-app/blob/7134dd0d5c15098abda3b96c5a2e1330e0c5c825/centml/templates/notebook-deployment.yaml#L74 
 2) For the service https://github.com/CentML/coreweave-app/blob/7134dd0d5c15098abda3b96c5a2e1330e0c5c825/centml/values.yaml#L6 I would suggest that you simplify this to just be 
 ```
 service:
   publicIP: true
  ```
  and template the annotations inside the service
  3) without looking at the templates https://github.com/CentML/coreweave-app/blob/7134dd0d5c15098abda3b96c5a2e1330e0c5c825/centml/values.yaml#L18 does not make much sense. Please change this to something like:
  ```
  storage:
    class: nvme
    size: 30Gi
  ```
  and then properly handle those fields in the pvc. 
  4) Please add a better description and icon to your Chart.yaml file 
  5) As far as I can tell https://github.com/CentML/coreweave-app/blob/7134dd0d5c15098abda3b96c5a2e1330e0c5c825/centml/values.yaml#L14 currently does not do anything. Please correct this or remove it. If you choose to remove it please add an external DNS record to the service. My preference would be to disable public IP by default and enable an ingress following something similar to our documentation here: https://docs.coreweave.com/coreweave-kubernetes/exposing-applications#example-manifest-2
  
Once you can resolve these things we can keep moving forward. Just to put those next steps on your horizon:
1) We will designate a webhook that you can reach to push packages to/from. 
2) This repo should use github actions to send a request to the webhook with the version and url for the release. 
3) Our CI will run and once we approve the release it will go into production.
